name: CI devops 2025

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn clean verify

      - name: Analyse SonarCloud
        working-directory: simple-api
        run: |
          mvn verify \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=alinahas1311_devopsTD2 \
            -Dsonar.organization=alinahas1311 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Alerte en cas d'échec des tests (rollback info)
        if: failure()
        run: |
          echo "❌ Les tests ont échoué pour le commit $GITHUB_SHA"
          echo "🛑 Le commit doit être corrigé ou reverté manuellement."
          echo "💡 Conseil : ouvrez une issue ou faites un git revert."
